import groovyx.gpars.GParsPool

import java.util.concurrent.atomic.AtomicInteger
import groovy.transform.BaseScript

@BaseScript CcdAnalysis script

@Grab("org.codehaus.gpars:gpars:1.2.1")
/**
 * This script prints the frequency of each Lab Result section in the CCD
 * Created by penny.lischer on 10/23/14.
 */

def labCounters=[labTest:0, date:0, numberOfCCDWithLabs:0, nullLabs:0]

def arrayOfFiles = files


def parallelCollection = GParsPool.withPool {

    arrayOfFiles.eachParallel { File file ->

        def xml = new XmlSlurper().parse(file.newInputStream())
        def sections = xml.component.structuredBody.component.section

        sections.each { section ->
            def sectionName = section.code.@code.text()

            synchronized (labCounters) {
                if (sectionName == "30954-2") {

                    boolean firstTimeIn = true;

                    def entries = section.entry;
                    if (entries.size() != 0) {
                        entries.each { entry ->
                            def observation = entry.procedure.entryRelationship.organizer.component.observation
                            String referenceValue = observation.text.reference.@value.text().replace('#', '')
//                            println 'REF: ' + referenceValue

                            if(referenceValue) {
                                //search for matching lab test title
                                def textBody = section.text.table.tbody
                                def usdLabRef = textBody.depthFirst().find {it.@ID.text().equalsIgnoreCase(referenceValue)}

                                if (usdLabRef) {
                                    def labTestName = usdLabRef.text()

                                    if (labTestName) {
                                        if (firstTimeIn) {
                                            labCounters['numberOfCCDWithLabs']++;
                                            firstTimeIn = false;
                                        }

                                        //Lab Test
                                        if (labTestName) {
                                            labCounters['labTest']++
                                        }

                                        //Lab Date
                                        def labDate = observation.effectiveTime.@value.text();
                                        if (labDate) {
                                            labCounters['date']++
                                        }
                                    } else {
                                        labCounters['nullLabs']++;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

println "Number of CCDS with Lab Results: " + labCounters.get('numberOfCCDWithLabs')
println 'Percent of Lab Results that contain one test in each CCDS: ' + (labCounters.get('numberOfCCDWithLabs')/arrayOfFiles.size()) *100 + '%';
println 'Number of Labs Tests Not Null in all CCDs: ' + labCounters.get('labTest')
println "Lab Date:" + labCounters.get('date')
println 'Number of Null Labs: ' + labCounters.get('nullLabs')
println "Lab Result Source: Not in CCD - generated by the HealthLogix instance and stored in the C-CDA"
